---
title: "Data Visualization"
author: "Swati Jani Joshi"
date: "June 30, 2016"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Titanic

R Markdown containig the code for Data Visualization Titanic exercise.

#### Load Data
```{r}
library(dplyr)
library(tidyr)
library(ggplot2)
titanic <- read.csv("~/Documents/Data Wrangling/DW_2/titanic_original.csv")
```

#### Structure of titanic
```{r}
str(titanic)
```

#### ggplot() for the first instruction
```{r}
ggplot(titanic, aes(x=factor(pclass), fill=factor(sex))) + geom_bar(position="dodge")
```

#### ggplot() for the second instruction
```{r}
ggplot(titanic, aes(x=factor(pclass), fill=factor(sex))) + geom_bar(position="dodge") +
  facet_grid(".~survived")
```

#### Position jitter (use below)
```{r}
posn.j <- position_jitter(0.5, 0)
```

#### ggplot() for the last instruction
```{r}
ggplot(titanic, aes(x=factor(pclass), y=age, col=factor(sex))) + 
  geom_jitter(position=posn.j, size=3, alpha=0.5) + facet_grid(".~survived")
```